"use client";

import "./workbench.css";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";

type Step = { number?: number; action: string; test_data?: string; expected_result?: string; locator_requirement?: string; assertion?: Record<string, unknown> };
type TestCase = { id: string; requirement_id: string; title: string; test_type: string; priority: string; status: string; steps: Step[]; expected_results?: string[]; [key: string]: unknown };
type Target = { application_url: string; authentication_type: string; browser: string; headless: boolean; username_label: string; password_label: string; submit_label: string; guidance: string };
type Requirement = { id: string; title: string; user_story: string; acceptance_criteria: string[]; source_files: string[]; analysis: Record<string, unknown>; target?: Target | null; cases: TestCase[]; locators: Locator[] };
type Locator = { id?: string; element: string; tag: string; xpath: string; validated: boolean; confidence: number; candidates: Array<{ kind: string; value: string; valid: boolean }> };
type Run = { id: string; started_at: string; status: string; browser: string; environment: string; summary: Record<string, number> };
type Suite = { id: string; name: string; description: string; case_count: number; case_ids: string[] };
type SettingsView = { llm_provider: string; llm_configured: boolean; browser: string; timeout_ms: number; execution_enabled: boolean; storage: string };
type Report = { runs: Run[]; results: Array<Record<string, unknown>>; counts: Record<string, number>; pass_rate: number };
type RuntimeCredentials = { username: string; password: string };

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";
const sections = ["Overview", "Requirements", "Test case generation", "Test cases", "Find elements", "Script generation", "Test execution", "Execution history", "Reporting", "Suites", "Settings"];
const emptyTarget = (url = ""): Target => ({ application_url: url, authentication_type: "No Authentication", browser: "chromium", headless: true, username_label: "", password_label: "", submit_label: "", guidance: "" });

async function api<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { ...(options?.body instanceof FormData ? {} : options?.body ? { "Content-Type": "application/json" } : {}), ...options?.headers }, cache: "no-store" });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof payload.detail === "string" ? payload.detail : "The request could not be completed.");
  return payload as T;
}

export default function Workbench() {
  const [section, setSection] = useState("Overview");
  const [dashboard, setDashboard] = useState({ requirements: 0, test_cases: 0, results: 0, status_counts: {} as Record<string, number> });
  const [requirements, setRequirements] = useState<Requirement[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [selected, setSelected] = useState<Requirement | null>(null);
  const [allCases, setAllCases] = useState<TestCase[]>([]);
  const [runs, setRuns] = useState<Run[]>([]);
  const [suites, setSuites] = useState<Suite[]>([]);
  const [report, setReport] = useState<Report | null>(null);
  const [settings, setSettings] = useState<SettingsView | null>(null);
  const [credentialsByStory, setCredentialsByStory] = useState<Record<string, RuntimeCredentials>>({});
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  async function refresh(id = selectedId) {
    const [summary, stories, cases, history, savedSuites, reportData, settingsData] = await Promise.all([
      api<typeof dashboard>("/api/dashboard"), api<Requirement[]>("/api/requirements"), api<TestCase[]>("/api/cases"), api<Run[]>("/api/runs"), api<Suite[]>("/api/suites"), api<Report>("/api/report"), api<SettingsView>("/api/settings"),
    ]);
    setDashboard(summary); setRequirements(stories); setAllCases(cases); setRuns(history); setSuites(savedSuites); setReport(reportData); setSettings(settingsData);
    const nextId = id || stories[0]?.id || "";
    setSelectedId(nextId);
    if (nextId) setSelected(await api<Requirement>(`/api/requirements/${nextId}`)); else setSelected(null);
  }

  useEffect(() => { refresh().catch((reason: Error) => setError(reason.message)); }, []);

  async function act(label: string, operation: () => Promise<void>) {
    setBusy(label); setError(""); setNotice("");
    try { await operation(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); }
  }

  async function chooseStory(event: ChangeEvent<HTMLSelectElement>) {
    const id = event.target.value; setSelectedId(id); setError("");
    try { setSelected(await api<Requirement>(`/api/requirements/${id}`)); } catch (reason) { setError((reason as Error).message); }
  }

  const casesForStory = allCases.filter((item) => !selectedId || item.requirement_id === selectedId);
  const title = section === "Overview" ? "Automation workspace" : section;

  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">FQ</span><div><strong>Fieldnotes</strong><small>QA workbench</small></div></div><nav>{sections.map((item, index) => <button key={item} className={section === item ? "active" : ""} onClick={() => setSection(item)}><span className="nav-number">{String(index + 1).padStart(2, "0")}</span>{item}</button>)}</nav><div className="sidebar-foot"><span className="status-dot" /> API online<div>{settings?.storage ?? "Checking storage..."}</div></div></aside>
    <section className="content"><header className="topbar"><div><p className="eyebrow">Fieldnotes QA / {String(sections.indexOf(section) + 1).padStart(2, "0")}</p><h1>{title}</h1><p className="lede">Requirements, reviewed cases, scripts and execution evidence in one workspace.</p></div><div className="topbar-actions"><span className="env-pill">{settings?.execution_enabled ? "BROWSER READY" : "BROWSER WORKER REQUIRED"}</span><button className="avatar" aria-label="Refresh workspace" title="Refresh workspace" onClick={() => act("Refreshing workspace...", async () => refresh())}>FQ</button></div></header>
      {busy && <div className="loading-banner" role="status"><span className="loader" />{busy}</div>}{error && <div className="alert error">{error}</div>}{notice && <div className="alert success">{notice}</div>}
      <StoryPicker requirements={requirements} selectedId={selectedId} onChange={chooseStory} />
      {section === "Overview" && <Overview dashboard={dashboard} requirements={requirements} cases={allCases} runs={runs} navigate={setSection} />}
      {section === "Requirements" && <RequirementsView requirements={requirements} selected={selected} onUpload={(files) => act("Analyzing requirement documents...", async () => { const body = new FormData(); files.forEach((file) => body.append("files", file)); const result = await api<{ requirement: Requirement; mode: string; session_credentials?: RuntimeCredentials }>("/api/requirements/analyze", { method: "POST", body }); if (result.session_credentials) setCredentialsByStory((current) => ({ ...current, [result.requirement.id]: result.session_credentials! })); setNotice(`Requirement analyzed (${result.mode}).`); await refresh(result.requirement.id); })} onDelete={() => selected && act("Deleting requirement and linked cases...", async () => { await api(`/api/requirements/${selected.id}`, { method: "DELETE" }); setCredentialsByStory((current) => { const next = { ...current }; delete next[selected.id]; return next; }); setNotice("Requirement and its dependent cases deleted."); await refresh(""); })} />}
      {section === "Test case generation" && <GenerationView selected={selected} onGenerate={() => selected && act("Generating positive and negative case drafts...", async () => { const result = await api<{ mode: string }>(`/api/requirements/${selected.id}/generate`, { method: "POST" }); setNotice(`Cases generated (${result.mode}).`); await refresh(selected.id); })} />}
      {section === "Test cases" && <CasesView cases={casesForStory} onUpdate={(item) => act("Saving test case...", async () => { await api(`/api/cases/${item.id}`, { method: "PUT", body: JSON.stringify(item) }); setNotice("Case saved."); await refresh(selectedId); })} onDelete={(id) => act("Deleting test case...", async () => { await api(`/api/cases/${id}`, { method: "DELETE" }); setNotice("Case deleted."); await refresh(selectedId); })} onRegenerate={(id) => act("Regenerating selected scenario...", async () => { await api(`/api/cases/${id}/regenerate`, { method: "POST" }); setNotice("Case regenerated; review approval was reset."); await refresh(selectedId); })} />}
      {section === "Find elements" && <ElementsView selected={selected} settings={settings} credentials={credentialsByStory[selectedId] ?? { username: "", password: "" }} onCredentialsChange={(credentials) => setCredentialsByStory((current) => ({ ...current, [selectedId]: credentials }))} onSaveTarget={(target) => selected && act("Saving target configuration...", async () => { await api(`/api/requirements/${selected.id}/target`, { method: "PUT", body: JSON.stringify(target) }); setNotice("Target settings saved for this story."); await refresh(selected.id); })} onDiscover={(target, credentials) => selected && act("Inspecting the target page and validating controls...", async () => { const result = await api<{ count: number }>(`/api/requirements/${selected.id}/discover`, { method: "POST", body: JSON.stringify({ target, credentials }) }); if (credentials) setCredentialsByStory((current) => ({ ...current, [selected.id]: credentials })); setNotice(`Found ${result.count} controls.`); await refresh(selected.id); })} />}
      {section === "Script generation" && <ScriptsView cases={casesForStory} selected={selected} onMessage={setNotice} run={act} />}
      {section === "Test execution" && <ExecutionView cases={casesForStory} selected={selected} settings={settings} credentials={credentialsByStory[selectedId] ?? { username: "", password: "" }} onCredentialsChange={(credentials) => setCredentialsByStory((current) => ({ ...current, [selectedId]: credentials }))} onExecute={(item, credentials) => act(`Executing ${item.id}...`, async () => { await api(`/api/cases/${item.id}/execute`, { method: "POST", body: JSON.stringify({ case_id: item.id, credentials }) }); setNotice(`${item.id} finished; see execution history for evidence.`); await refresh(selectedId); })} />}
      {section === "Execution history" && <HistoryView runs={runs} />}
      {section === "Reporting" && <ReportingView report={report} runs={runs} />}
      {section === "Suites" && <SuitesView suites={suites} cases={allCases} onSave={(suite) => act("Saving test suite...", async () => { await api("/api/suites", { method: "POST", body: JSON.stringify(suite) }); setNotice("Suite created."); await refresh(selectedId); })} onDelete={(id) => act("Deleting suite...", async () => { await api(`/api/suites/${id}`, { method: "DELETE" }); setNotice("Suite deleted."); await refresh(selectedId); })} />}
      {section === "Settings" && <SettingsView settings={settings} />}
      <footer><span>Fieldnotes QA / API v1.0</span><span>Streamlit remains available locally for functional validation.</span></footer>
    </section>
  </main>;
}

function StoryPicker({ requirements, selectedId, onChange }: { requirements: Requirement[]; selectedId: string; onChange: (event: ChangeEvent<HTMLSelectElement>) => void }) {
  return <div className="story-picker"><label htmlFor="active-story">Active story</label><select id="active-story" value={selectedId} onChange={onChange}><option value="">Select a story</option>{requirements.map((item) => <option key={item.id} value={item.id}>{item.id} / {item.title}</option>)}</select><span>{requirements.length} saved</span></div>;
}

function Overview({ dashboard, requirements, cases, runs, navigate }: { dashboard: { requirements: number; test_cases: number; results: number; status_counts: Record<string, number> }; requirements: Requirement[]; cases: TestCase[]; runs: Run[]; navigate: (value: string) => void }) {
  const pass = dashboard.status_counts.PASS ?? 0; const fail = dashboard.status_counts.FAIL ?? 0;
  return <><div className="metrics"><Metric label="Requirements" value={dashboard.requirements} detail="source stories" /><Metric label="Test cases" value={dashboard.test_cases} detail="draft and approved" /><Metric label="Executed" value={dashboard.results} detail="persisted outcomes" /><Metric label="Pass rate" value={pass + fail ? `${Math.round(pass / (pass + fail) * 100)}%` : "--"} detail={`${pass} passed / ${fail} failed`} /></div><div className="work-grid"><section className="panel"><Heading kicker="Workflow" title="Move from story to evidence" /><div className="stage-list">{[["01", "Requirements", "Analyze source documents."], ["02", "Test case generation", "Create positive and negative drafts."], ["03", "Test cases", "Edit, review, approve or reject."], ["04", "Find elements", "Inspect the story's shared controls."], ["05", "Script generation", "Generate and edit Playwright scripts."], ["06", "Test execution", "Run approved cases and inspect evidence."]].map(([number, target, text]) => <button key={number} onClick={() => navigate(target)}><b>{number}</b><span><strong>{target}</strong><small>{text}</small></span><i>→</i></button>)}</div></section><section className="panel"><Heading kicker="Recent activity" title="Latest runs" /><div className="case-list">{runs.slice(0, 6).map((run) => <div className="case-row" key={run.id}><span className="case-status">{run.status}</span><div><strong>{run.id}</strong><small>{run.started_at} / {run.browser}</small></div></div>)}{!runs.length && <Empty>No execution runs yet.</Empty>}</div></section></div><section className="panel cases-panel"><Heading kicker="Workspace" title="Requirements and case health" /><div className="overview-split"><div><Metric label="Requirements" value={requirements.length} detail="stories tracked" /></div><div><Metric label="Drafts awaiting review" value={cases.filter((item) => item.status === "Draft").length} detail="human approval required" /></div><div><Metric label="Approved for execution" value={cases.filter((item) => item.status === "Approved").length} detail="ready when a worker is connected" /></div></div></section></>;
}

function RequirementsView({ requirements, selected, onUpload, onDelete }: { requirements: Requirement[]; selected: Requirement | null; onUpload: (files: File[]) => void; onDelete: () => void }) {
  const [files, setFiles] = useState<File[]>([]);
  const totalBytes = files.reduce((sum, file) => sum + file.size, 0);
  return <div className="view-grid"><section className="panel"><Heading kicker="Source intake" title="Analyze requirement documents" /><p className="muted">Upload up to ten PDF, DOCX, XLSX, CSV, TXT or Markdown files. Credentials in source documents are extracted locally and redacted from model prompts.</p><label className="dropzone"><input type="file" multiple accept=".txt,.md,.markdown,.pdf,.docx,.csv,.xlsx" onChange={(event) => setFiles(Array.from(event.target.files ?? []))} /><span className="upload-symbol">+</span><strong>{files.length ? `${files.length} file(s) selected` : "Choose requirement documents"}</strong><small>{files.map((file) => file.name).join(" · ") || "Combined upload limit: 4 MB"}</small></label><button className="primary" disabled={!files.length || files.length > 10 || totalBytes > 4 * 1024 * 1024} onClick={() => files.length > 0 && onUpload(files)}>Analyze documents</button>{totalBytes > 4 * 1024 * 1024 && <p className="upload-error">Keep the combined document size below 4 MB.</p>}</section><section className="panel"><Heading kicker="Saved stories" title={`${requirements.length} requirements`} /><div className="case-list">{requirements.map((item) => <article className={`case-row ${item.id === selected?.id ? "selected-row" : ""}`} key={item.id}><div><strong>{item.title}</strong><small>{item.id} / {item.acceptance_criteria?.length ?? 0} criteria</small></div></article>)}{!requirements.length && <Empty>Upload the first requirement to start.</Empty>}</div>{selected && <div className="detail-block"><h3>{selected.user_story || selected.title}</h3><ul>{selected.acceptance_criteria?.map((criterion, index) => <li key={index}>{criterion}</li>)}</ul><small>Source files: {selected.source_files?.join(", ") || "None"}</small><div><button className="danger-button" onClick={onDelete}>Delete requirement and dependent cases</button></div></div>}</section></div>;
}

function GenerationView({ selected, onGenerate }: { selected: Requirement | null; onGenerate: () => void }) {
  return <section className="panel"><Heading kicker="Drafting" title="Generate reviewable test cases" /><p className="muted">Creates positive and negative test cases from the active story's acceptance criteria. Existing approved/rejected cases are kept; previous drafts for this story are replaced.</p>{selected ? <><div className="story-callout"><strong>{selected.title}</strong><p>{selected.user_story || "No story text supplied."}</p><ul>{selected.acceptance_criteria?.map((item, index) => <li key={index}>{item}</li>)}</ul></div><button className="primary compact" onClick={onGenerate}>Generate case drafts</button></> : <Empty>Select or create a requirement first.</Empty>}</section>;
}

function CasesView({ cases, onUpdate, onDelete, onRegenerate }: { cases: TestCase[]; onUpdate: (item: TestCase) => void; onDelete: (id: string) => void; onRegenerate: (id: string) => void }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("All"); const [activeId, setActiveId] = useState("");
  const filtered = cases.filter((item) => (!query || `${item.id} ${item.title}`.toLowerCase().includes(query.toLowerCase())) && (status === "All" || item.status === status));
  const active = filtered.find((item) => item.id === activeId) ?? filtered[0];
  return <div className="panel"><Heading kicker="Human review" title="Test cases" /><div className="filters"><input placeholder="Search cases" value={query} onChange={(event) => setQuery(event.target.value)} /><select value={status} onChange={(event) => setStatus(event.target.value)}>{["All", "Draft", "Approved", "Rejected"].map((value) => <option key={value}>{value}</option>)}</select><ExportButton format="json" requirementId={cases[0]?.requirement_id} statusFilter={status === "All" ? undefined : status} /><ExportButton format="xlsx" requirementId={cases[0]?.requirement_id} statusFilter={status === "All" ? undefined : status} /></div><div className="case-list">{filtered.map((item) => <button className={`case-row case-select ${active?.id === item.id ? "selected-row" : ""}`} key={item.id} onClick={() => setActiveId(item.id)}><span className={`case-status ${item.status.toLowerCase()}`}>{item.status}</span><div><strong>{item.title}</strong><small>{item.id} / {item.test_type} / {item.priority} / {item.steps?.length ?? 0} steps</small></div></button>)}{!filtered.length && <Empty>No cases match these filters.</Empty>}</div>{active && <CaseEditor key={active.id} item={active} onUpdate={onUpdate} onDelete={() => onDelete(active.id)} onRegenerate={() => onRegenerate(active.id)} />}</div>;
}

function CaseEditor({ item, onUpdate, onDelete, onRegenerate }: { item: TestCase; onUpdate: (item: TestCase) => void; onDelete: () => void; onRegenerate: () => void }) {
  const [draft, setDraft] = useState(item);
  function patchStep(index: number, key: keyof Step, value: string) { setDraft((current) => ({ ...current, steps: current.steps.map((step, stepIndex) => stepIndex === index ? { ...step, [key]: value } : step) })); }
  return <div className="detail-block editor"><Heading kicker={`${item.id} / ${item.status}`} title="Edit and review" /><label>Title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><div className="form-row"><label>Type<input value={draft.test_type} onChange={(event) => setDraft({ ...draft, test_type: event.target.value })} /></label><label>Priority<select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value })}>{["High", "Medium", "Low"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Review status<select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })}>{["Draft", "Approved", "Rejected"].map((value) => <option key={value}>{value}</option>)}</select></label></div>{draft.steps?.map((step, index) => <div className="step-editor" key={index}><h4>Step {index + 1}</h4><label>Action<input value={step.action} onChange={(event) => patchStep(index, "action", event.target.value)} /></label><div className="form-row"><label>Test data<input value={step.test_data ?? ""} onChange={(event) => patchStep(index, "test_data", event.target.value)} /></label><label>Locator requirement<input value={step.locator_requirement ?? ""} onChange={(event) => patchStep(index, "locator_requirement", event.target.value)} /></label></div><label>Expected result<input value={step.expected_result ?? ""} onChange={(event) => patchStep(index, "expected_result", event.target.value)} /></label></div>)}<div className="button-row"><button className="primary compact" onClick={() => onUpdate(draft)}>Save case</button><button className="secondary compact" onClick={() => onUpdate({ ...draft, status: "Approved" })}>Approve</button><button className="text-button" onClick={onRegenerate}>Regenerate scenario</button><button className="danger-button" onClick={onDelete}>Delete</button></div><div className="expectations"><strong>Expected results</strong>{item.expected_results?.map((result, index) => <p key={index}>{result}</p>)}</div></div>;
}

function ElementsView({ selected, settings, credentials, onCredentialsChange, onSaveTarget, onDiscover }: { selected: Requirement | null; settings: SettingsView | null; credentials: RuntimeCredentials; onCredentialsChange: (credentials: RuntimeCredentials) => void; onSaveTarget: (target: Target) => void; onDiscover: (target: Target, credentials?: RuntimeCredentials) => void }) {
  const [target, setTarget] = useState<Target>(emptyTarget());
  useEffect(() => { setTarget(selected?.target ? { ...emptyTarget(), ...selected.target } : emptyTarget()); }, [selected?.id, selected?.target]);
  function update(key: keyof Target, value: string | boolean) { setTarget((current) => ({ ...current, [key]: value })); }
  return <div className="view-grid"><section className="panel"><Heading kicker="Story-scoped environment" title="Find and validate elements" /><TargetFields target={target} update={update} /><button className="secondary compact" onClick={() => onSaveTarget(target)} disabled={!selected || !target.application_url}>Save target settings</button>{target.authentication_type === "Username & Password" && <div className="credential-grid"><label>Session username<input autoComplete="username" value={credentials.username} onChange={(event) => onCredentialsChange({ ...credentials, username: event.target.value })} /></label><label>Session password<input type="password" autoComplete="current-password" value={credentials.password} onChange={(event) => onCredentialsChange({ ...credentials, password: event.target.value })} /></label></div>}<button className="primary compact" disabled={!selected || !settings?.execution_enabled || !target.application_url || (target.authentication_type === "Username & Password" && (!credentials.username || !credentials.password))} onClick={() => onDiscover(target, target.authentication_type === "Username & Password" ? credentials : undefined)}>Discover shared elements</button>{!settings?.execution_enabled && <div className="callout warning">Live DOM discovery needs a browser worker. Vercel's serverless function does not include browser binaries; configure an execution worker to enable it.</div>}</section><section className="panel"><Heading kicker="Shared locator repository" title={`${selected?.locators?.length ?? 0} saved elements`} />{selected?.locators?.length ? selected.locators.map((locator, index) => <article className="locator-row" key={locator.id ?? `${locator.element}-${index}`}><span className={locator.validated ? "locator-valid" : "locator-invalid"}>{locator.validated ? "VALID" : "CHECK"}</span><div><strong>{locator.element}</strong><small>{locator.tag} / {locator.xpath}</small><small>{locator.candidates?.filter((candidate) => candidate.valid).length ?? 0} valid alternatives / confidence {Math.round((locator.confidence ?? 0) * 100)}%</small></div></article>) : <Empty>Save a target and scan from a browser worker to populate shared locators.</Empty>}</section></div>;
}

function TargetFields({ target, update }: { target: Target; update: (key: keyof Target, value: string | boolean) => void }) {
  return <div className="target-form"><label>Application URL<input value={target.application_url} onChange={(event) => update("application_url", event.target.value)} placeholder="https://qa.example.com" /></label><div className="form-row"><label>Authentication<select value={target.authentication_type} onChange={(event) => update("authentication_type", event.target.value)}><option>No Authentication</option><option>Username &amp; Password</option><option>SSO</option></select></label><label>Browser<select value={target.browser} onChange={(event) => update("browser", event.target.value)}>{["chromium", "firefox", "webkit"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Mode<select value={target.headless ? "headless" : "headed"} onChange={(event) => update("headless", event.target.value === "headless")}><option>headless</option><option>headed</option></select></label></div>{target.authentication_type === "Username & Password" && <div className="form-row"><label>Username field label<input value={target.username_label} onChange={(event) => update("username_label", event.target.value)} /></label><label>Password field label<input value={target.password_label} onChange={(event) => update("password_label", event.target.value)} /></label><label>Submit label<input value={target.submit_label} onChange={(event) => update("submit_label", event.target.value)} /></label></div>}<label>Discovery guidance<textarea value={target.guidance} onChange={(event) => update("guidance", event.target.value)} /></label></div>;
}

function ScriptsView({ cases, selected, onMessage, run }: { cases: TestCase[]; selected: Requirement | null; onMessage: (message: string) => void; run: (label: string, operation: () => Promise<void>) => Promise<void> }) {
  const [caseId, setCaseId] = useState(""); const [source, setSource] = useState(""); const active = cases.find((item) => item.id === caseId) ?? cases[0];
  useEffect(() => { if (active) { setCaseId(active.id); api<{ source: string }>(`/api/cases/${active.id}/script`).then((result) => setSource(result.source)).catch(() => setSource("")); } else setSource(""); }, [active?.id]);
  async function generate() { if (!active) return; await run("Generating Playwright script...", async () => { const result = await api<{ source: string }>(`/api/cases/${active.id}/script`, { method: "POST", body: JSON.stringify({ case_id: active.id }) }); setSource(result.source); onMessage("Generated script. Review and save it before use."); }); }
  async function save() { if (!active) return; await run("Validating and saving script...", async () => { await api(`/api/cases/${active.id}/script`, { method: "PUT", body: JSON.stringify({ source }) }); onMessage("Script saved to version history."); }); }
  function download() { if (!active || !source) return; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([source], { type: "text/x-python" })); link.download = `${active.id}.py`; link.click(); URL.revokeObjectURL(link.href); }
  return <section className="panel"><Heading kicker="Script review" title="Generate and edit Playwright scripts" /><div className="filters"><select value={active?.id ?? ""} onChange={(event) => setCaseId(event.target.value)}><option value="">Select test case</option>{cases.map((item) => <option key={item.id} value={item.id}>{item.id} / {item.title}</option>)}</select><span className="muted">{selected?.target?.application_url ?? "Configure this story's target first."}</span></div><textarea className="code-editor" spellCheck={false} value={source} onChange={(event) => setSource(event.target.value)} placeholder="Generate a script for a case with a saved target and reviewed locators." /><div className="button-row"><button className="primary compact" onClick={generate} disabled={!active}>Generate script</button><button className="secondary compact" onClick={save} disabled={!active || !source}>Validate and save</button><button className="text-button" onClick={download} disabled={!source}>Download .py</button></div></section>;
}

function ExecutionView({ cases, selected, settings, credentials, onCredentialsChange, onExecute }: { cases: TestCase[]; selected: Requirement | null; settings: SettingsView | null; credentials: RuntimeCredentials; onCredentialsChange: (credentials: RuntimeCredentials) => void; onExecute: (item: TestCase, credentials?: RuntimeCredentials) => Promise<void> }) {
  const approved = cases.filter((item) => item.status === "Approved");
  const auth = selected?.target?.authentication_type === "Username & Password";
  return <section className="panel"><Heading kicker="Approved cases only" title="Test execution" /><div className="callout warning">{settings?.execution_enabled ? "Browser execution is enabled for this service." : "Execution is unavailable on this Vercel serverless deployment. Connect a browser worker; the same endpoint can then execute approved cases and persist step evidence."}</div>{auth && <div className="credential-grid"><label>Session username<input autoComplete="username" value={credentials.username} onChange={(event) => onCredentialsChange({ ...credentials, username: event.target.value })} /></label><label>Session password<input type="password" autoComplete="current-password" value={credentials.password} onChange={(event) => onCredentialsChange({ ...credentials, password: event.target.value })} /></label></div>}<div className="button-row"><button className="primary compact" disabled={!approved.length || !settings?.execution_enabled || (auth && (!credentials.username || !credentials.password))} onClick={async () => { for (const item of approved) await onExecute(item, auth ? credentials : undefined); }}>Execute all approved ({approved.length})</button></div><div className="case-list">{approved.map((item) => <article className="case-row" key={item.id}><span className="case-status approved">Approved</span><div><strong>{item.title}</strong><small>{item.id} / {item.steps.length} steps</small></div><button className="secondary compact" disabled={!settings?.execution_enabled || (auth && (!credentials.username || !credentials.password))} onClick={() => onExecute(item, auth ? credentials : undefined)}>Run case</button></article>)}{!approved.length && <Empty>Approve cases in Test cases before running them.</Empty>}</div><p className="muted">Each case runs in an isolated browser. Results appear in execution history; batches continue to the next case after an individual failure.</p></section>;
}

function HistoryView({ runs }: { runs: Run[] }) {
  const [runId, setRunId] = useState(""); const [detail, setDetail] = useState<{ run: Run; results: Array<Record<string, unknown>> } | null>(null);
  useEffect(() => { const chosen = runs.find((item) => item.id === runId) ?? runs[0]; if (chosen) { setRunId(chosen.id); api<typeof detail>(`/api/runs/${chosen.id}`).then(setDetail).catch(() => setDetail(null)); } else setDetail(null); }, [runId, runs.length]);
  return <section className="panel"><Heading kicker="Traceability" title="Execution history" /><select className="wide-select" value={runId} onChange={(event) => setRunId(event.target.value)}>{runs.map((item) => <option key={item.id} value={item.id}>{item.id} / {item.started_at} / {item.status}</option>)}</select>{detail ? <><div className="button-row"><EvidenceDownloadButton runId={detail.run.id} /></div><div className="metrics compact-metrics">{Object.entries(detail.run.summary ?? {}).map(([key, value]) => <Metric key={key} label={key} value={value} detail="run summary" />)}</div>{detail.results.map((result, index) => <article className="result-panel" key={`${result.id}-${index}`}><h3>{String(result.title ?? result.test_case_id)} / {String(result.status)}</h3><p>{String(result.error || "No test-level error.")}</p><pre>{JSON.stringify(result.steps, null, 2)}</pre></article>)}</> : <Empty>No persisted runs. Browser execution must complete on a service with durable storage.</Empty>}</section>;
}

function ReportingView({ report, runs }: { report: Report | null; runs: Run[] }) {
  const [runId, setRunId] = useState("All runs"); const [requirementId, setRequirementId] = useState("All requirements"); const [priority, setPriority] = useState("All priorities"); const [status, setStatus] = useState("All statuses"); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState("");
  const sourceRows = report?.results ?? [];
  const requirementOptions = Array.from(new Set(sourceRows.map((item) => String(item.requirement_id ?? "Unknown"))));
  const priorityOptions = Array.from(new Set(sourceRows.map((item) => String(item.priority ?? "Unknown"))));
  const rows = sourceRows.filter((item) => { const date = String(item.run_started_at ?? "").slice(0, 10); return (runId === "All runs" || item.run_id === runId) && (requirementId === "All requirements" || item.requirement_id === requirementId) && (priority === "All priorities" || item.priority === priority) && (status === "All statuses" || item.status === status) && (!fromDate || date >= fromDate) && (!toDate || date <= toDate); }); const counts: Record<string, number> = {}; const priorityCounts: Record<string, Record<string, number>> = {};
  rows.forEach((row) => { const outcome = String(row.status); const level = String(row.priority ?? "Unknown"); counts[outcome] = (counts[outcome] ?? 0) + 1; priorityCounts[level] ??= {}; priorityCounts[level][outcome] = (priorityCounts[level][outcome] ?? 0) + 1; }); const executed = (counts.PASS ?? 0) + (counts.FAIL ?? 0); const maxPriorityCount = Math.max(1, ...Object.values(priorityCounts).flatMap(Object.values));
  return <section className="panel"><Heading kicker="Persisted outcomes" title="Reporting" /><div className="filters"><select value={runId} onChange={(event) => setRunId(event.target.value)}><option>All runs</option>{runs.map((run) => <option key={run.id} value={run.id}>{run.id}</option>)}</select><select value={requirementId} onChange={(event) => setRequirementId(event.target.value)}><option>All requirements</option>{requirementOptions.map((value) => <option key={value}>{value}</option>)}</select><select value={priority} onChange={(event) => setPriority(event.target.value)}><option>All priorities</option>{priorityOptions.map((value) => <option key={value}>{value}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)}><option>All statuses</option>{["PASS", "FAIL", "BLOCKED", "SKIPPED"].map((value) => <option key={value}>{value}</option>)}</select><label className="date-filter">From<input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label className="date-filter">To<input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label><ReportExportButton rows={rows} format="json" /><ReportExportButton rows={rows} format="csv" /></div><div className="metrics"><Metric label="Total" value={rows.length} detail="filtered results" /><Metric label="Passed" value={counts.PASS ?? 0} detail="PASS" /><Metric label="Failed" value={counts.FAIL ?? 0} detail="FAIL" /><Metric label="Blocked" value={counts.BLOCKED ?? 0} detail="BLOCKED" /><Metric label="Pass rate" value={executed ? `${Math.round((counts.PASS ?? 0) / executed * 100)}%` : "--"} detail="PASS / (PASS + FAIL)" /></div><div className="report-charts"><div><h3>Status distribution</h3>{["PASS", "FAIL", "BLOCKED", "SKIPPED"].map((value) => <DistributionBar key={value} label={value} value={counts[value] ?? 0} max={Math.max(1, ...Object.values(counts))} />)}</div><div><h3>Outcomes by priority</h3>{Object.entries(priorityCounts).map(([level, outcomes]) => <DistributionBar key={level} label={level} value={Object.values(outcomes).reduce((sum, value) => sum + value, 0)} max={maxPriorityCount} />)}</div></div><div className="table-wrap"><table><thead><tr>{["Run", "Case", "Title", "Requirement", "Status", "Priority", "Duration", "Browser"].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.id}-${index}`}>{["run_id", "test_case_id", "title", "requirement_id", "status", "priority", "duration", "browser"].map((field) => <td key={field}>{String(row[field] ?? "-")}</td>)}</tr>)}</tbody></table></div>{!rows.length && <Empty>Reports include saved execution outcomes only; drafts and scripts are not counted as runs.</Empty>}</section>;
}

function SuitesView({ suites, cases, onSave, onDelete }: { suites: Suite[]; cases: TestCase[]; onSave: (suite: { name: string; description: string; case_ids: string[] }) => void; onDelete: (id: string) => void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [ids, setIds] = useState<string[]>([]);
  function submit(event: FormEvent) { event.preventDefault(); if (name.trim()) { onSave({ name: name.trim(), description, case_ids: ids }); setName(""); setDescription(""); setIds([]); } }
  return <div className="view-grid"><section className="panel"><Heading kicker="Reusable groups" title="Test suites" /><form className="target-form" onSubmit={submit}><label>Suite name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Description<input value={description} onChange={(event) => setDescription(event.target.value)} /></label><fieldset><legend>Cases</legend>{cases.map((item) => <label className="check-row" key={item.id}><input type="checkbox" checked={ids.includes(item.id)} onChange={(event) => setIds(event.target.checked ? [...ids, item.id] : ids.filter((id) => id !== item.id))} />{item.id} / {item.title}</label>)}</fieldset><button className="primary compact">Create suite</button></form></section><section className="panel"><Heading kicker="Saved collections" title={`${suites.length} suites`} />{suites.map((suite) => <article className="suite-row" key={suite.id}><div><strong>{suite.name}</strong><p>{suite.description}</p><small>{suite.case_ids?.length ?? suite.case_count} cases</small></div><button className="danger-button" onClick={() => onDelete(suite.id)}>Delete</button></article>)}{!suites.length && <Empty>Create a suite to group cases for repeatable runs.</Empty>}</section></div>;
}

function SettingsView({ settings }: { settings: SettingsView | null }) {
  return <section className="panel"><Heading kicker="Environment" title="Settings and service readiness" /><div className="settings-grid"><Setting label="LLM provider" value={settings?.llm_provider ?? "Loading"} /><Setting label="LLM credentials" value={settings?.llm_configured ? "Configured" : "Offline draft mode"} /><Setting label="Browser" value={settings?.browser ?? "Loading"} /><Setting label="Timeout" value={`${settings?.timeout_ms ?? "-"} ms`} /><Setting label="Execution" value={settings?.execution_enabled ? "Enabled" : "Worker required"} /><Setting label="Persistence" value={settings?.storage ?? "Loading"} /></div><div className="callout warning"><strong>Production storage note</strong><br />Vercel /tmp storage is temporary and isolated between function instances. Configure a durable database before treating requirement, suite, script, or run records as production-persistent. LLM/API secrets must be configured in deployment environment settings, never in browser storage.</div><p className="muted">Streamlit keeps its session-specific provider settings in memory. Production provider and security settings are server-managed environment variables.</p></section>;
}

function ExportButton({ format, requirementId, statusFilter }: { format: string; requirementId?: string; statusFilter?: string }) {
  async function download() { try { const query = new URLSearchParams({ format }); if (requirementId) query.set("requirement_id", requirementId); if (statusFilter) query.set("status_filter", statusFilter); const response = await fetch(`${API_BASE}/api/export/cases?${query}`); if (!response.ok) throw new Error("Export failed"); const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `test-cases.${format === "markdown" ? "md" : format}`; link.click(); URL.revokeObjectURL(link.href); } catch { window.alert("Export could not be downloaded."); } }
  return <button className="outline-button" onClick={download}>Export {format.toUpperCase()}</button>;
}

function ReportExportButton({ rows, format }: { rows: Array<Record<string, unknown>>; format: "json" | "csv" }) {
  function download() { const columns = Array.from(new Set(rows.flatMap((row) => Object.keys(row)))); const content = format === "json" ? JSON.stringify(rows, null, 2) : [columns.join(","), ...rows.map((row) => columns.map((key) => `"${String(row[key] ?? "").replaceAll('"', '""')}"`).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: format === "json" ? "application/json" : "text/csv" })); link.download = `execution-report.${format}`; link.click(); URL.revokeObjectURL(link.href); }
  return <button className="outline-button" onClick={download}>Download report {format.toUpperCase()}</button>;
}

function EvidenceDownloadButton({ runId }: { runId: string }) {
  async function download() { try { const response = await fetch(`${API_BASE}/api/export/evidence/${runId}`); if (!response.ok) throw new Error(); const link = document.createElement("a"); link.href = URL.createObjectURL(await response.blob()); link.download = `${runId}-evidence.zip`; link.click(); URL.revokeObjectURL(link.href); } catch { window.alert("Evidence archive could not be downloaded."); } }
  return <button className="outline-button" onClick={download}>Download run evidence ZIP</button>;
}

function Metric({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function Heading({ kicker, title }: { kicker: string; title: string }) { return <div className="section-heading"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div></div>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="empty">{children}</div>; }
function Setting({ label, value }: { label: string; value: string }) { return <div className="setting-row"><small>{label}</small><strong>{value}</strong></div>; }
function DistributionBar({ label, value, max }: { label: string; value: number; max: number }) { return <div className="distribution-row"><span>{label}</span><div><i style={{ width: `${Math.max(value ? 3 : 0, Math.round(value / max * 100))}%` }} /></div><strong>{value}</strong></div>; }